version: '3.7'

services:
  go-rabbit-mq:
    container_name: go-rabbit-mq
    image: rabbitmq:3.6-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabitmq:/etc/rabbitmq/
    networks:
      - go-network

  go-rest-mock:
    container_name: go-rest-mock
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 4000 -w db.json
    ports:
      - 4000:4000
    volumes:
      - ./mocks/rest:/data
    restart: unless-stopped
    networks:
      - go-network

volumes:
  rabitmq:

networks:
  go-network:
    driver: bridge